from pydantic import BaseModel, Field
from typing import List, Dict, Any, Union
from datetime import datetime

# =================================================================
# UNIVERSAL API RESPONSE WRAPPER
# =================================================================

class APIResponse(BaseModel):
    """
    Universal schema for all query outputs, as required by the user.
    The 'data' field is defined as a list of dictionaries (Dict[str, Any])
    because the keys are dynamically generated by the SQL service function.
    """
    count: int = Field(..., description="The total number of records returned in the 'data' list.")
    key: List[str] = Field(..., description="A list of string keys (column names) present in each object in the 'data' list.")
    data: List[Dict[str, Any]] = Field(..., description="The list of results, where each item is a dictionary matching the 'key' list.")


